### ISSUE TITLE
AJAX form submission

### ISSUE THREAD

**Issue by PeteAndersen** [imorente/gatsby-netlify-form-example#1]
I was hoping to start a discussion on a way to do AJAX form submission with Gatsby and Netlify. Following Netlify's [React example](https://www.netlify.com/blog/2017/07/20/how-to-integrate-netlifys-form-handling-in-a-react-app/) was resulting in a strange 404 error on POST request, and the server was actually returning the Gatsby 404 page. I was under the impression that Netlify would be intercepting this request but that doesn't seem to be working out. Have you tried it out and had any success?

**Comment by imorente** [comment]
Hi Pete 👋 

You should send the POST request to a page on your app that does exist. For instance, in the [React example](https://www.netlify.com/blog/2017/07/20/how-to-integrate-netlifys-form-handling-in-a-react-app/) you mention, I post to `/`

Is there a particular reason you prefer submitting the form to a page that doesn't exist?

**Comment by PeteAndersen** [comment]
Oh neat, I just noticed you were the author of that post! I am indeed POSTing to `/`, and I also tried posting to the same page the form was on (`/contact`). Both return a 404 and the response is the Gatsby generated 404 page. I'm trying to figure out which piece of the puzzle I'm missing - does Netlify acknowledge any POST with www-form-urlencoded header and a `form-name` piece of data in there as a valid form submission? Or does it require the `<input type="hidden" name="form-name" value="contact" />` element in the actual form HTML for it to accept the POST request?

**Comment by imorente** [comment]
Not sure what issue you might be running into :( 

I copied the code from the stateful form example into the contact page in this repo, and the form submission worked, both with and without the `<input type="hidden" name="form-name" value="contact" />` element.

<img width="666" alt="screen shot 2017-10-16 at 12 00 40 am" src="https://user-images.githubusercontent.com/83225/31599212-3dd62a02-b206-11e7-8d37-27a145f0bfa7.png">

You can take a look at the deploy preview for the PR https://github.com/imorente/gatsby-netlify-form-example/pull/2 at https://deploy-preview-2--gatsby-form-example.netlify.com/contact/

Is the app you're struggling with in a public repo I can clone to try it out?

**Comment by PeteAndersen** [comment]
I was going to post a gist with my form, but noticed that my fetch request had `'form-name': 'content'` instead of `contact`. The form is named `contact`. Very silly issue that took me a very long time to notice :( 

I guess the takeaway is that Netlify doesn't blindly accept any POST request w/ form data as a valid form submission. It has to exist as an HTML element somewhere on the page with matching names, as your blog post made abundantly clear. Thanks for your time!

**Comment by pablo67340** [comment]
Sorry to reopen such an old issue, I have followed basically every tutorial online and I keep running into the same issue. I have no idea what I am doing wrong. I am not getting a 404 response, but rather a 200 response with no content, and no submissions are actually added. If I change the form-name hidden value to something that doesnt match my real HTML form, I get 404...as expected. I do not understand why I am getting a 200 response (meaning netlify is digesting it) but no submissions are added. @imorente Is there any chance you could help?

Here is my react component: https://pastebin.com/pwLAB6Uy

(Due to privacy of the website, placeholder content has been inserted)

The form has popped up in my Forms tab, but with 0 submissions. Lastly, I notice under the Headers everything appears to be present. form-name with all my data is sent in the body. However, I also notice that in the "timing" tab, it says "Caution: Request is not finished yet!"

https://gyazo.com/7ae7edc51b5c8f2e8145caa1483d7c48
https://gyazo.com/2ef1ef2dd1f0a0c81cf651bb70df1089

Hopefully I provided enough detail to figure out this issue. Any assistance would be great!
